version: '3.8'

services:
 
  participa:
    extends:
        file: participa/docker-compose.yml
        service: participa
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER:?error}
      - DB_PASSWORD=${POSTGRES_PASSWORD:?error}
      - DB_NAME=${POSTGRES_DB:?error}
      - DB_PORT=${POSTGRES_PORT:?error}
    networks:
        - polis-net
    depends_on:
      - "postgres"

  server:
      extends:
        file: polis/docker-compose.yml
        service: server
      build:
        target: dev
        args:
          NODE_ENV: development

  math:
    extends:
        file: polis/docker-compose.yml
        service: math
    ports:
      # nrepl port
      - "18975:18975"
    environment:
      CHOKIDAR_USEPOLLING: "true"

  postgres:
    extends:
        file: polis/docker-compose.yml
        service: postgres
    restart: "no"
    ports:
      - "54000:5432"

  file-server:
    extends:
        file: polis/docker-compose.yml
        service: file-server
    build:
      args:
        NODE_ENV: development

  nginx-proxy:
    extends:
        file: polis/docker-compose.yml
        service: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/participa/staticfiles
      - media_volume:/participa/mediafiles
    depends_on:
      - "server"
      - "participa"

  maildev:
    image: docker.io/maildev/maildev:1.1.1
    labels:
      polis_tag: ${TAG}
    ports:
      # User interface
      - "1080:1080"
      # SMTP port
      - "1025:1025"

networks:
  polis-net:

volumes:
  backups:
    labels:
      polis_tag: ${TAG:-dev}
  postgres:
    labels:
      polis_tag: ${TAG:-dev}
  server-logs:
    labels:
      polis_tag: ${TAG:-dev}
  media_volume:
  static_volume:
  redis_volume:
